LibraryProject/LibraryProject/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using LibraryProject.Models;

namespace LibraryProject.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        LibraryDBEntities1 db = new LibraryDBEntities1();
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Indexx(Account t)
        {
            var query = db.Accounts.FirstOrDefault(x => x.KullaniciAdi == t.KullaniciAdi && x.Sifre == t.Sifre);
            if (query != null)
            {
                FormsAuthentication.SetAuthCookie(query.KullaniciAdi, false);
                ViewBag.hata = "";
                return RedirectToAction("Index", "Admin");
            }

            else
            {
                ViewBag.hata = "Kullanıcı adınız veya şifreniz hatalı";
                return View();
            }

        }
    }
}

LibraryProject/LibraryProject/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V16</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
    <link rel="icon" type="image/png" href="../../Login/images/icons/favicon.ico" />
    
    <link rel="stylesheet" type="text/css" href="../../Login/vendor/bootstrap/css/bootstrap.min.css">
  
    <link rel="stylesheet" type="text/css" href="../../Login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    
    <link rel="stylesheet" type="text/css" href="../../Login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
  
    <link rel="stylesheet" type="text/css" href="../../Login/vendor/animate/animate.css">
   
    <link rel="stylesheet" type="text/css" href="../../Login/vendor/css-hamburgers/hamburgers.min.css">
  
    <link rel="stylesheet" type="text/css" href="../../Login/vendor/animsition/css/animsition.min.css">
  
    <link rel="stylesheet" type="text/css" href="../../Login/vendor/select2/select2.min.css">
   
    <link rel="stylesheet" type="text/css" href="../../Login/vendor/daterangepicker/daterangepicker.css">
  
    <link rel="stylesheet" type="text/css" href="../../Login/css/util.css">
    <link rel="stylesheet" type="text/css" href="../../Login/css/main.css">
   
</head>
<body>
    @using (Html.BeginForm("Indexx", "Login", FormMethod.Post, new { @class = "kt-form", role = "form" }))
    {
        <div class="limiter">
                <div class="container-login100" style=" background-image: url('../../Login/images/bg-01.jpg'); ">
                    <div class="wrap-login100 p-t-30 p-b-50">
                        <span class="login100-form-title p-b-41">
                            Account Login
                        </span>
                        <form class="login100-form validate-form p-b-33 p-t-5">

                            <div class="wrap-input100 validate-input" data-validate="Enter username">
                                <input class="input100" type="text" name="KullaniciAdi" placeholder="User name">
                                <span class="focus-input100" data-placeholder="&#xe82a;"></span>
                            </div>

                            <div class="wrap-input100 validate-input" data-validate="Enter password">
                                <input class="input100" type="password" name="Sifre" placeholder="Password">
                                <span class="focus-input100" data-placeholder="&#xe80f;"></span>
                            </div>

                            <div class="container-login100-form-btn m-t-32">
                                <button type="submit" class="login100-form-btn">
                                    Login
                                </button>
                            </div>



                        </form>
                    </div>
                </div>
            </div>
       
    }


    <div id="dropDownSelect1"></div>



    <script src="../../Login/vendor/jquery/jquery-3.2.1.min.js"></script>

    <script src="../../Login/vendor/animsition/js/animsition.min.js"></script>


    <script src="../../Login/vendor/bootstrap/js/popper.js"></script>
    <script src="../../Login/vendor/bootstrap/js/bootstrap.min.js"></script>


    <script src="../../Login/vendor/select2/select2.min.js"></script>

    <script src="../../Login/vendor/daterangepicker/moment.min.js"></script>
    <script src="../../Login/vendor/daterangepicker/daterangepicker.js"></script>

    <script src="../../Login/vendor/countdowntime/countdowntime.js"></script>


    <script src="../../Login/js/main.js"></script>

</body>
</html>


@*<html>
<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style>
        div {
            text-align: center;
        }

        .div1 {
            background-color: white;
            margin-left: 350px;
            margin-top: 50px;
            height: 400px;
            width: 400px;
            border-style: solid;
            border-color: black;
        }
    </style>
</head>
<body>
    <div class="div1">
        <label style="background-color: #93BFA3; font-size: 30px">Giriş Sayfası</label>
        @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "kt-form", role = "form" }))
        {


            <label style="margin-top:100px;">Kullanıcı Adınız</label><br />
            <input name="KullaniciAdi" />
            <br />
            <label>Şifreniz</label><br />
            <input type="password" name="Sifre" />
            @ViewBag.hata

            <br />
            <br />
            <button type="submit" class="btn btn-success btn-elevate btn-pill btn-elevate-air" style="font-size:1.2rem;">Giriş Yap</button>


        }
        <br />


    </div>
</body>
</html>*@